### ISSUE TITLE
Use pre-built binary for macOS

### ISSUE THREAD

**Issue by gmile** [tclass/homebrew-cloud_sql_proxy#3]
The "[Connecting using the Cloud SQL Proxy](https://cloud.google.com/sql/docs/postgres/connect-admin-proxy)" page lists a method of installing `cloud_sql_proxy` that does not require compiling from sources.

The URL for the binary is the following:

```
https://dl.google.com/cloudsql/cloud_sql_proxy.darwin.amd64
```

Perhaps this tap could be updated to utilize the pre-built binary?

All latest pre-built binaries also exist here: https://github.com/GoogleCloudPlatform/cloudsql-proxy/releases

**Comment by tclass** [comment]
sry for answering that late. I'm actually not sure about all the advantages/disadvantges here, some people might wanna build it themselves? Just downloading the binary sure is convenient, not sure if it's nessecary

**Comment by gmile** [comment]
@tclass (opinion) I _think_ most people would want to just install the tool without making modifications, installing go tooling, etc. We may disagree on this, as I am not sure my assumption are entirely correct though since I don't know the audience of the tool much. But given Google itself promotes downloading of binary package, perhaps doing so considered a default option most people would want to go with?

What do you think about making utilising formula syntax that allows use of both [`head`](https://rubydoc.brew.sh/Formula#head-class_method) and [`stable`](https://rubydoc.brew.sh/Formula#stable-class_method) blocks, e.g. to support both to-be-compiled and stable version of tool?

**Comment by tclass** [comment]
how would that look like? Can you pass in a parameter into `brew install`?

**Comment by gmile** [comment]
@tclass yes, there's a way to express "[install from HEAD](https://github.com/Homebrew/brew/blob/3476ca7b8ff889ef61e65783d35d1b2073bd4012/Library/Homebrew/cmd/install.rb#L76-L78)" in `brew install`. For [example](https://github.com/Homebrew/homebrew-core/blob/master/Formula/git.rb#L8):

```bash
brew install --HEAD git
```

**Comment by tclass** [comment]
Do you wanna implement that feature and create a PR?
